### PR TITLE
[iec6205621meter Binding] Fix ArrayIndexOutOfBoundsException

### LINKED ISSUE #4651: Problems with iec6205621meter Bindings
## Context

I encouter irregular ArrayIndexOutOfBoundsException while reading iec6205621meter Values.
In 5 readings i encounter 3 times an error, 2 times everthing is fine!
is it possible to have a bugfix?
## My Environment
- OpenHAB v1.8.3-001 on Synology DS 412+ DSM 6.0.2-8451 Update 1
- Landis & gyr E350 Meter
- Weidmann Serial USB IR Head
## Current Behavior

When i read the Meter manualy , i have the following output:

Commands:
echo -n -e '\x2F\x3F\x21\x0D\x0A' > /dev/ttyUSB0
echo -n -e '\x06\x30\x30\x30\x0D\x0A' > /dev/ttyUSB0
`
/LGZ4ZMF100AC.M23
F.F(00)
0.0(            7156)
C.1.0(11894619)
C.1.1(        )
1.8.1(007987.101*kWh)
1.8.2(007211.594*kWh)
2.8.1(000000.000*kWh)
2.8.2(000000.000*kWh)
1.8.0(015198.695*kWh)
2.8.0(000000.000*kWh)
15.8.0(015198.695*kWh)
C.7.0(0015)
32.7(228*V)
52.7(227*V)
72.7(228*V)
31.7(000.06*A)
51.7(000.42*A)
71.7(000.04*A)
82.8.1(0000)
82.8.2(0000)
0.2.0(M23)
C.5.0(0400)
!
`
Here the error description:

`12:24:17.306 DEBUG o.o.b.i.i.Iec6205621MeterBinding[:120] - Read meter: meter1; /dev/ttyUSB0
12:24:31.799 ERROR o.o.c.s.AbstractActiveService[:175] - Error while executing background thread iec6205621meter Refresh Service
java.lang.ArrayIndexOutOfBoundsException: 4100
    at org.openmuc.j62056.Connection.bytesToHex(Connection.java:606)
    at org.openmuc.j62056.Connection.read(Connection.java:453)
    at org.openhab.binding.iec6205621meter.internal.Meter.read(Meter.java:83)
    at org.openhab.binding.iec6205621meter.internal.Iec6205621MeterBinding.execute(Iec6205621MeterBinding.java:121)
    at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156)
    at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173)
`
if the reading went well, the log tells me the following:

`12:23:02.845 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 0AC.M23;;
12:23:02.846 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 0)
0.0;            7156;
12:23:02.846 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: C.1.0;11894619;
12:23:02.847 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: C.1.1;        ;
12:23:02.847 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 1.8.1;007987.079;kWh
12:23:02.847 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 1.8.2;007211.594;kWh
12:23:02.848 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 2.8.1;000000.000;kWh
12:23:02.848 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 2.8.2;000000.000;kWh
12:23:02.848 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 1.8.0;015198.674;kWh
12:23:02.849 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 2.8.0;000000.000;kWh
12:23:02.849 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 15.8.0;015198.674;kWh
12:23:02.849 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: C.7.0;0015;
12:23:02.850 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 32.7;230;V
12:23:02.850 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 52.7;229;V
12:23:02.850 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 72.7;229;V
12:23:02.851 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 31.7;000.07;A
12:23:02.851 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 51.7;000.41;A
12:23:02.852 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 71.7;000.03;A
12:23:02.852 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 82.8.1;0000;
12:23:02.852 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 82.8.2;0000;
12:23:02.853 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: 0.2.0;M23;
12:23:02.853 DEBUG o.o.b.i.internal.Meter[:85] - DataSet: C.5.0;0400;`

Thanks in advance for further investigation!
Kind regards Walo
##

### PR DESCRIPTION
**Pull request by 9037568**
Trap ArrayIndexOutOfBoundsException in the bytesToHexString() method.
When encountered, fall back to a simpler method of conversion.

Fixes #4651.

### CODE REVIEW

**Comment by watou** [comment]
Could this method be replaced by using something like `org.apache.commons.codec.binary.Hex.encodeHexString(bytes)`?

**Comment by 9037568** [comment]
I agree that's a better solution.  I'll push another change.

**Comment by watou** [comment]
LGTM

**Comment by 9037568** [comment]
Thanks!

**Comment by 9037568** [comment]
Cherry-picked to 1.9.x.

**Pull request merged**
