### PR TITLE
[Weather] Remove the Weather Underground provider

### PR DESCRIPTION
**Pull request by 9037568**
Remove the Weather Underground provider and clean up old references to the Yahoo provider.

See also #5760

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Please remove the changes on the year in the headers - this is taken care of by https://github.com/openhab/openhab1-addons/pull/5756 (which I just merged now as nobody else did ;-).

**Comment by 9037568** [comment]
I put the dates back but it's still complaining about the deleted file. Should I try rebasing to master?

**Comment by kaikreuzer** [comment]
Yes, rebasing should help.

**Comment by 9037568** [comment]
I think this should be good to go, now.

**Pull request merged**
