### PR TITLE
[Cardio2e][Documentation] Added README.md

### PR DESCRIPTION
**Pull request by magd1978**

### CODE REVIEW

**Comment by magd1978** [comment]
I have finished writing the binding documentation and I have uploaded it in .MD format.
Sorry for the delay and sorry for the errors when doing the pull request.
What is missing so that the binding can be included in the openHAB distribution?
Thank you.

**Comment by 9037568** [comment]
This file needs to be formatted as an .MD file, not as HTML.

You could start by using a converter like [this one](https://www.browserling.com/tools/html-to-markdown).

**Comment by magd1978** [comment]
The required changes have been made, and the format has been improved.
Thanks for your corrections.

**Comment by 9037568** [comment]
I don't have an answer for that question. Perhaps @kaikreuzer or @sjka can comment.

**Comment by sjka** [comment]
My knowledge about openHAB packaging pretty much ends with what is written here: https://docs.openhab.org/developers/development/bindings.html#include-the-binding-in-the-build-and-the-distro. I guess that'll be a good starting point though.

**Comment by kaikreuzer** [comment]
As this is an openHAB 1 binding, you might rather want to have a look at https://www.openhab.org/docs/developer/development/compatibilitylayer.html#how-to-add-a-successfully-tested-1-x-add-on-to-the-distribution.

**Comment by sjka** [comment]
Argh, how could I miss that "little" detail...? Sorry!

**Comment by magd1978** [comment]
Thank you very much!!

**Pull request merged**
