### PR TITLE
[modbus] README fix for write syntax

### PR DESCRIPTION
**Pull request by ssalonen**

### CODE REVIEW

**Comment by 9037568** [comment]
Thanks, @ssalonen !

**Comment by ssalonen** [comment]
Hi,

The docs still at http://docs.openhab.org/addons/bindings/modbus1/readme.html seem to be wrong

See [extended format](http://docs.openhab.org/addons/bindings/modbus1/readme.html#extended-format) write example.

Are the docs deployed automatically?

Best,
Sami

**Comment by ssalonen** [comment]
@9037568 do you know why the docs are not updated at http://docs.openhab.org/addons/bindings/modbus1/readme.html#extended-format ?

**Comment by 9037568** [comment]
Unfortunately, I don't.  I saw Kai was having some problems with the build recently. It's possible there's a relationship there.

**Pull request merged**
