### PR TITLE
Fix markdown; change back to LF

### PR DESCRIPTION
**Pull request by watou**
@theoweiss:

I changed the markdown to work at docs.openhab.org  (every heading and code block needs a blank line above and below).  Also regenerated the TOC.  If you have edits in progress, please recreate these changes in your copy.  Otherwise, please OK this PR.  Thanks!

Signed-off-by: John Cocula <john@cocula.com>

### CODE REVIEW

**Comment by watou** [comment]
As the version on docs.openhab.org has serious Markdown rendering problems (different renderer), I will merge this now and hopefully this does not cause any problems.

**Comment by theoweiss** [comment]
Thanks @watou !

**Comment by watou** [comment]
No problem! Please feel free to make any further changes.

**Comment by theoweiss** [comment]
@watou The page still doesn't render properly. Do you know what's going wrong?

**Comment by watou** [comment]
I think it's because the site hasn't been updated  since the merge.  (On mobile so it's hard to verify.) @kaikreuzer would have to regenerate the content.

**Pull request merged**
