### PR TITLE
[epsonprojector] Add additional ColorMode and AspectRatio values (from 5030UB projector)

### PR DESCRIPTION
**Pull request by jaydonoghue**
Added a couple new items that work with the 5030UB projector

### CODE REVIEW

**Comment by 9037568** [comment]
Thanks, @jaydonoghue !

**Comment by kaikreuzer** [comment]
It seems that this PR broke the build: https://openhab.ci.cloudbees.com/job/openHAB1-Addons/1458/console

@jaydonoghue Could you please have a look?

**Comment by jaydonoghue** [comment]
Yikes. Will fix. Looks like it doesn't like the dash 

 - J

**Comment by 9037568** [comment]
I'm going to revert this to fix the build.

**Comment by 9037568** [comment]
@jaydonoghue, I see you've fixed these in your repo. Would you care to submit a new PR?

**Pull request merged**
