### PR TITLE
[Weather] Allow Forecastio to request units other than SI

### PR DESCRIPTION
**Pull request by 9037568**
Fulfills feature request in #3062.

### CODE REVIEW

**Comment by 9037568** [comment]
Done. I will also update the wiki.

**Comment by 9037568** [comment]
Or should i not? I'm not clear on what the new process is. Are we still maintaining [this wiki](https://github.com/openhab/openhab1-addons/wiki/Weather-Binding), or do docs go somewhere else now?

**Comment by watou** [comment]
> Or should i not? I'm not clear on what the new process is. Are we still maintaining this wiki, or do docs go somewhere else now?

We're in the "in-between period," where we can't yet refer OH2 users to docs.openhab.org for 1.x addon documentation, so until then all OH1 and OH2 users must refer to the wiki.  So please update the wiki, and would you mind also updating org.openhab.binding.weather/README.md on the [PR](https://github.com/openhab/openhab1-addons/pull/5029) we've been working on?

**Comment by 9037568** [comment]
>...please update with wiki, and would you mind also updating org.openhab.binding.weather/README.md on the PR we've been working on?

I'll do both of those. Thanks!

**Pull request merged**
