### PR TITLE
5202 snmp memory leak fix

### PR DESCRIPTION
**Pull request by sconwayaus**
Fixed Memory leak in SNMP Binding

### CODE REVIEW

**Comment by martinvw** [comment]
Can you squash your commits and optionally change commit message to include a fixes #5202 then it will auto close the related issue :-)

For squashing / rebasing see:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by martinvw** [comment]
After squashing you should force push to overwrite the existing commits :-)

**Comment by sconwayaus** [comment]
Ok, I think I got this time. Gits still very new to me. 

Cheers

**Comment by martinvw** [comment]
Perfect
LGTM!

**Comment by 9037568** [comment]
Thank you both!

**Comment by sconwayaus** [comment]
Looks like the issue didn't auto close as I referenced the pull request instead of the Issue.

Is there anything you need me to do to fix?

**Comment by martinvw** [comment]
Hmm, that was my example 😀

**Pull request merged**
