### PR TITLE
[JDBC/MySQL Persistence] Updated connector to version 8.0

### PR DESCRIPTION
**Pull request by s4ndst0rm**
Is backwards compatible to V5

### CODE REVIEW

**Comment by 9037568** [comment]
Has this change received any community testing?
@lewie can you review?

**Comment by s4ndst0rm** [comment]
It is the addition to #5699 
Currently i removed the v5 driver and load the v8 driver manually

[Openhab Thread](https://community.openhab.org/t/mysql-8-0/54547)

**Comment by 9037568** [comment]
@s4ndst0rm can you fix the pom.xml conflicts?

**Comment by s4ndst0rm** [comment]
@9037568 Done.

**Comment by 9037568** [comment]
Thanks to @lewie for the review.
Thanks to @s4ndst0rm for the update!

**Pull request merged**
