### PR TITLE
[modbus] Eventually close borrowed connections also when config changes

### LINKED ISSUE #5078: [Modbus] Binding restarts service after config change - keeping serial port open
Trying to figure out parameters for a modbus serial device I changed modbus.cfg several times.
Changing setting sometimes seems to restart the addon.

What I noticed was that after such a restart the addon stopped working.
Checking the logs I found entries like this:

> 19:08:04.715 [ERROR] [et.wimpi.modbus.net.SerialConnection] - open port failed: Modbus Serial Master
> 19:08:04.717 [ERROR] [ing.ModbusSlaveConnectionFactoryImpl] - connect try 1/3 error: open port failed: Modbus Serial Master. Connection SerialConnection@1e19c7d[portName=/dev/ttyUSB99,port=<null>]. Endpoint ModbusSerialSlaveEndpoint@1098b8e[portName=/dev/ttyUSB99]
> 19:08:34.754 [ERROR] [et.wimpi.modbus.net.SerialConnection] - open port failed: Modbus Serial Master
> 19:08:34.756 [ERROR] [ing.ModbusSlaveConnectionFactoryImpl] - connect try 2/3 error: open port failed: Modbus Serial Master. Connection SerialConnection@1e19c7d[portName=/dev/ttyUSB99,port=<null>]. Endpoint ModbusSerialSlaveEndpoint@1098b8e[portName=/dev/ttyUSB99]
> 19:09:04.793 [ERROR] [et.wimpi.modbus.net.SerialConnection] - open port failed: Modbus Serial Master
> 19:09:04.795 [ERROR] [ing.ModbusSlaveConnectionFactoryImpl] - connect try 3/3 error: open port failed: Modbus Serial Master. Connection SerialConnection@1e19c7d[portName=/dev/ttyUSB99,port=<null>]. Endpoint ModbusSerialSlaveEndpoint@1098b8e[portName=/dev/ttyUSB99]
> 19:09:04.796 [ERROR] [ing.ModbusSlaveConnectionFactoryImpl] - re-connect reached max tries 3, throwing last error: open port failed: Modbus Serial Master. Connection SerialConnection@1e19c7d[portName=/dev/ttyUSB99,port=<null>]. Endpoint ModbusSerialSlaveEndpoint@1098b8e[portName=/dev/ttyUSB99]
> 19:09:04.798 [ERROR] [ing.ModbusSlaveConnectionFactoryImpl] - Error connecting connection SerialConnection@1e19c7d[portName=/dev/ttyUSB99,port=<null>] for endpoint ModbusSerialSlaveEndpoint@1098b8e[portName=/dev/ttyUSB99]: open port failed: Modbus Serial Master
> 19:09:04.799 [WARN ] [.binding.modbus.internal.ModbusSlave] - ModbusSlave (eehtc): Error ...

The easiest way to see if that happend was that my adapter stopped blinking (no more traffic).

Restarting openhab2 fixes the problem.
At least until I make the next change to modbus.cfg

Environment:
Openhab2 on raspberry pi 3
Serial: FTDI USB Serial converter FT232RL
Editing of modbus.cfg was made via a windows client using the openHAB-conf share.
see: https://community.openhab.org/t/modubs-configuration-for-ee800-device/21274/14

### PR DESCRIPTION
**Pull request by ssalonen**
Also regression test introduced.

Fixes #5078

Signed-off-by: Sami Salonen <ssalonen@gmail.com>

Pre-compiled version for testing available below in the [new comment](https://github.com/openhab/openhab1-addons/pull/5088#issuecomment-279857656)

(old download link for reference
```
( _Old buggy version (4ef8d43): [org.openhab.binding.modbus-1.10.0-SNAPSHOT.jar.zip](https://github.com/openhab/openhab1-addons/files/772494/org.openhab.binding.modbus-1.10.0-SNAPSHOT.jar.zip)_ )
````
)

### CODE REVIEW

**Comment by ssalonen** [comment]
Let's wait.

Looking at the test with fresh eyes I also noticed something peculiar -- I need to check it out further

**Comment by ssalonen** [comment]
OK while looking at the "expected results" I found out additional bug with transaction IDs. Race conditions were possible which lead to too eager discard of the messages. See the commit messages for more information.

I had to modify the expected results and I now think those make more sense. I added comments to the test to make the reasoning more transparent.

Do you want me to create separate bug for the transaction ID issue?


Best,
Sami

**New download link for the 0d7c5ed**
[org.openhab.binding.modbus-1.10.0-SNAPSHOT-plus-transaction-id-race-condition.fix.jar.zip](https://github.com/openhab/openhab1-addons/files/775454/org.openhab.binding.modbus-1.10.0-SNAPSHOT-plus-transaction-id-race-condition.fix.jar.zip)

**Comment by ssalonen** [comment]
Fixed some logging related stuff with transaction id mismatch in 	823e664 and 48a3ee3.

Testing with the community [on this thread](https://community.openhab.org/t/modbus-lag/11786/12). User sipvoip has several "transaction id errors", not sure what causes them but good to test if the fixes in this branch help.

Latest version attached

[org.openhab.binding.modbus-1.10.0-SNAPSHOT-48a3ee3.zip](https://github.com/openhab/openhab1-addons/files/784896/org.openhab.binding.modbus-1.10.0-SNAPSHOT-48a3ee3.zip)

**Comment by ssalonen** [comment]
Fixed some logging related stuff in 	823e664, 48a3ee3 and 175604. 

Testing with the community [on this thread](https://community.openhab.org/t/modbus-lag/11786/12). User sipvoip has several "transaction id errors", not sure what causes them but good to test if the fixes in this branch help.

Latest version attached

[org.openhab.binding.modbus-1.10.0-SNAPSHOT-175604.zip](https://github.com/openhab/openhab1-addons/files/784910/org.openhab.binding.modbus-1.10.0-SNAPSHOT-175604.zip)

**Comment by ssalonen** [comment]
Forgot to update community user sipvoip case here: we managed to have it working successfully in the end. We seemed to fix the issues with his modbus slave by re-using the same connection and not closing after every request. The issues were apparently how the slave handles connection disconnect sequence (SYN/FIN etc.).

Please let me know if I can help reviewing this PR in any way. @manniat, have you had to test this one out?

Best
Sami

**Comment by 9037568** [comment]
I don't see a need for an additional PR for the transaction ID issue. Let's just include it here.

**Comment by ssalonen** [comment]
Rebased the code and run the Eclipse format.

**Comment by ssalonen** [comment]
@9037568  Everything good to merge?

**Comment by 9037568** [comment]
Yep, good to go if you're ok with it.

**Comment by ssalonen** [comment]
I'm good. Seems like we are not getting response from original reporter.

**Comment by 9037568** [comment]
Thanks!

**Pull request merged**
