### PR TITLE
[Yamaha binding] Add netradio support

### PR DESCRIPTION
**Pull request by sumnerboy12**

### CODE REVIEW

**Comment by ScheissSchiesser** [comment]
Could somebody add details to the Yamaha-Binding configuration page on the wiki as to how to use this NetRadio functionality? I apologize if this is not the right forum for this. Please let me know where to post about this.

**Comment by watou** [comment]
The [wiki page](https://github.com/openhab/openhab/wiki/Yamahareceiver-Binding) appears to cover the netRadio functionality of the binding.  Please discuss at https://community.openhab.org if it's giving you trouble.

**Comment by ScheissSchiesser** [comment]
The wiki page you linked shows only the following under the "allowed binding types": 
power, mute, volume, input, surroundProgram

NetRadio binding type is included in the example, but nothing is explained regarding how it works. It would be very helpful if there was a little explanation. Explain a bit to me here and I would be happy to submit a PR for the wiki (if that's allowed).

**Comment by watou** [comment]
>  The wiki page you linked shows only the following under the "allowed binding types": 
power, mute, volume, input, surroundProgram

You're right, a little explanation would be helpful beyond the [example](https://github.com/openhab/openhab/wiki/Yamahareceiver-Binding#example).

If you can locate a reliable explanation to include in the text of the wiki page, most likely from the [community site](https://community.openhab.org/), feel free to add the missing information [here](https://github.com/openhab/openhab/wiki/Yamahareceiver-Binding/_edit) (no PR necessary, just be careful! 😄 ).

**Comment by Mikypan81** [comment]
Hello, I've a Yamaha receiver RX/V475 but have some problems to select net radio channel.
I've discovered on the net this code that should allow to select net radio channel on yamaha receiver but I'm not a programmer and I don't know how to edit a jar binding, so I paste here the code, maybe someone can help me to make a try....
The only way to select a station is a solution like the following way:

 public void setNetRadio(int lineNo) throws IOException {
        /* Jump to specified line in preset list */
        postAndGetResponse("<?xml version=\"1.0\" encoding=\"utf-8\"?><YAMAHA_AV cmd=\"PUT\"><NET_RADIO><List_Control><Jump_Line>"
                + "1</Jump_Line><Cursor>Sel</Cursor></List_Control></NET_RADIO></YAMAHA_AV>");
        try {
          Thread.currentThread().sleep(1000);
        } catch(InterruptedException ex) {
          Thread.currentThread().interrupt();
        }
        postAndGetResponse("<?xml version=\"1.0\" encoding=\"utf-8\"?><YAMAHA_AV cmd=\"PUT\"><NET_RADIO><List_Control><Jump_Line>"
                + "1</Jump_Line><Cursor>Sel</Cursor></List_Control></NET_RADIO></YAMAHA_AV>");
        try {
          Thread.currentThread().sleep(1000);
        } catch(InterruptedException ex) {
          Thread.currentThread().interrupt();

        }
        postAndGetResponse("<?xml version=\"1.0\" encoding=\"utf-8\"?><YAMAHA_AV cmd=\"PUT\"><NET_RADIO><List_Control><Jump_Line>"
                + lineNo + "</Jump_Line><Cursor>Sel</Cursor></List_Control></NET_RADIO></YAMAHA_AV>");
        postAndGetResponse("<?xml version=\"1.0\" encoding=\"utf-8\"?><YAMAHA_AV cmd=\"PUT\"><NET_RADIO><List_Control><Jump_Line>"
                + "Sel</Jump_Line><Cursor>Sel</Cursor></List_Control></NET_RADIO></YAMAHA_AV>");
    }

**Pull request merged**
