### PR TITLE
[MQTT] Fix the startup conflict between transport, action and binding

### LINKED ISSUE #5038: [MQTT with MQTT Action] MQTT Binding will not connect with action installed
Discussion on the forum is [here](https://community.openhab.org/t/mqtt-stopped-working-help/21192).

I can't say exactly which build this started. But it is a problem with 2.0.0 release.

## Expected Behavior

When I have both the MQTT binding and MQTT Action installed I expect to be able to publish messages through the action and publish/subscribe messages with the MQTT binding.

## Current Behavior

When the MQTT Action is installed the MQTT binding generates no Info level logging including the expected:

```
MQTT Service initialization completed.
Starting MQTT broker connection 'mosquitto'
```

No messages published to topics subscribed to are received by OH. No messages published by the action are received by the broker. These were confirmed using mosquitto_sub.

Putting the binding into TRACE level the only logs generated by the binding are as follows:

```
2017-01-25 16:10:36.964 [mqtt                      ] - BundleEvent STARTING - org.openhab.binding.mqtt
2017-01-25 16:10:36.968 [MqttActivator             ] - MQTT binding has been started.
2017-01-25 16:10:36.971 [mqtt                      ] - BundleEvent STARTED - org.openhab.binding.mqtt
2017-01-25 16:10:37.604 [mqtt                      ] - ServiceEvent REGISTERED - {org.openhab.model.item.binding.BindingConfigReader, org.openhab.binding.mqtt.MqttBindingProvider}={component.name=org.openhab.binding.mqtt.genericbindingprovider, component.id=161, service.id=305, service.bundleid=193, service.scope=bundle} - org.openhab.binding.mqtt
2017-01-25 16:10:37.617 [MqttGenericBindingProvider] - Starting to load MQTT config for item vMBR_Temperature
2017-01-25 16:10:37.632 [MqttItemConfig            ] - Loaded MQTT config for item 'vMBR_Temperature' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.656 [MqttGenericBindingProvider] - Starting to load MQTT config for item vMBR_Humidity
2017-01-25 16:10:37.657 [MqttItemConfig            ] - Loaded MQTT config for item 'vMBR_Humidity' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.658 [MqttGenericBindingProvider] - Starting to load MQTT config for item vMBR_Light
2017-01-25 16:10:37.660 [MqttItemConfig            ] - Loaded MQTT config for item 'vMBR_Light' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.662 [MqttGenericBindingProvider] - Starting to load MQTT config for item vGarageOpener1
2017-01-25 16:10:37.664 [MqttItemConfig            ] - Loaded MQTT config for item 'vGarageOpener1' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.664 [MqttGenericBindingProvider] - Starting to load MQTT config for item vGarageOpener2
2017-01-25 16:10:37.668 [MqttItemConfig            ] - Loaded MQTT config for item 'vGarageOpener2' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.668 [MqttGenericBindingProvider] - Starting to load MQTT config for item vFrontDoor
2017-01-25 16:10:37.669 [MqttItemConfig            ] - Loaded MQTT config for item 'vFrontDoor' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.669 [MqttGenericBindingProvider] - Starting to load MQTT config for item vBackDoor
2017-01-25 16:10:37.670 [MqttItemConfig            ] - Loaded MQTT config for item 'vBackDoor' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.671 [MqttGenericBindingProvider] - Starting to load MQTT config for item vGarageDoor
2017-01-25 16:10:37.675 [MqttItemConfig            ] - Loaded MQTT config for item 'vGarageDoor' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.676 [MqttGenericBindingProvider] - Starting to load MQTT config for item vJennPhone_Cerberos_BT
2017-01-25 16:10:37.680 [MqttItemConfig            ] - Loaded MQTT config for item 'vJennPhone_Cerberos_BT' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.684 [MqttGenericBindingProvider] - Starting to load MQTT config for item vRichPhone_Cerberos_BT
2017-01-25 16:10:37.684 [MqttItemConfig            ] - Loaded MQTT config for item 'vRichPhone_Cerberos_BT' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.685 [MqttGenericBindingProvider] - Starting to load MQTT config for item vJennPhone_Hydra_BT
2017-01-25 16:10:37.686 [MqttItemConfig            ] - Loaded MQTT config for item 'vJennPhone_Hydra_BT' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.690 [MqttGenericBindingProvider] - Starting to load MQTT config for item vRichPhone_Hydra_BT
2017-01-25 16:10:37.691 [MqttItemConfig            ] - Loaded MQTT config for item 'vRichPhone_Hydra_BT' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.692 [MqttGenericBindingProvider] - Starting to load MQTT config for item vRichPhone_Chimera_BT
2017-01-25 16:10:37.692 [MqttItemConfig            ] - Loaded MQTT config for item 'vRichPhone_Chimera_BT' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.693 [MqttGenericBindingProvider] - Starting to load MQTT config for item vJennPhone_Chimera_BT
2017-01-25 16:10:37.693 [MqttItemConfig            ] - Loaded MQTT config for item 'vJennPhone_Chimera_BT' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.693 [MqttGenericBindingProvider] - Starting to load MQTT config for item vReelyActive_Cerberos
2017-01-25 16:10:37.694 [MqttItemConfig            ] - Loaded MQTT config for item 'vReelyActive_Cerberos' : 1 subscribers, 0 publishers
2017-01-25 16:10:37.695 [mqtt                      ] - ServiceEvent REGISTERED - {org.osgi.service.event.EventHandler}={event.topics=openhab/*, component.name=org.openhab.binding.mqtt.MqttItemBinding, component.id=163, service.id=307, service.bundleid=193, service.scope=bundle} - org.openhab.binding.mqtt
2017-01-25 16:10:37.704 [mqtt                      ] - ServiceEvent REGISTERED - {org.osgi.service.event.EventHandler, org.osgi.service.cm.ManagedService}={event.topics=openhab/*, service.pid=org.openhab.mqtt-eventbus, component.name=org.openhab.binding.mqtt.eventbus, component.id=162, service.id=308, service.bundleid=193, service.scope=bundle} - org.openhab.binding.mqtt
2017-01-25 16:10:37.721 [MqttEventBusBinding       ] - MQTT: Activating event bus binding.
2017-01-25 16:10:37.724 [MqttEventBusBinding       ] - No mqtt-eventbus properties configured.
```

Uninstalling both the MQTT binding and the MQTT action and just reinstalling the MQTT binding causes the subscription Items to start receiving their messages again.

## Steps to Reproduce (for bugs)

1. Install and configure the MQTT Binding and MQTT Action
2. Configure Items to subscribe to topics
3. Configure rule to publish to topic using publish()
4. Generate message traffic
5. Confirm message traffic is being received by the broker
6. Confirm message traffic is not being received by OH
7. Confirm messages published by OH are not received by the broker

## Context

For some time now MQTT has been central to my HA system. When I moved to OH2 I started using the MQTT action instead of MQTT outgoing Items. It worked for many months. I don't know exactly when it stopped working but it was within the past couple of weeks.

## Your Environment

* Version used: openHAB 2.0.0 Release Build with Release Build version of add-ons
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Latest Docker Image from openhab/openhab on Docker Hub configured with --net==host
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Latest version of docker running on Ubuntu 16.04 64-bit

### PR DESCRIPTION
**Pull request by 9037568**
This should fix the MQTT startup conflict by making all of the PID values distinct.

Fixes #5038

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I am not in the details of the MQTT 1.x support, but could you elaborate on why this should fix the issue? If the transport is meant to be configured (I so far always thought it is only the binding and the action), then this looks like a breaking change (all documentation would have to be adapted). If it doesn't require configuration, the pid could be removed completely.

**Comment by 9037568** [comment]
@sjka had commented in one of the [discussion threads](https://community.openhab.org/t/solved-mqtt-binding-stopped-working-after-todays-snapshot-update/19447/19?u=namraccr) the problem was conflicting PID values.

I hadn't considered it would be possible to remove one. 

At any rate, I'll remove the transport PID.

**Comment by kaikreuzer** [comment]
As I said, I didn't look into the code myself, so I cannot tell weather removing the pid is a valid option - there is likely some reason for it being there as it is (but also a reason for its value, so changing it without understanding the internals might be risky).

**Comment by 9037568** [comment]
So my first experiment with removing the PID from the transport did not go well. Appears to prevent the broker from starting at all. In addition to that, when I reverted back to the original version with the new PID, it didn't return to a working state.

Still experimenting...

**Comment by kaikreuzer** [comment]
Closing due to inactivity.

**Pull request closed without merging**
