### PR TITLE
[caldav_personal] add calendar type property

### PR DESCRIPTION
**Pull request by querdenker2k**

### CODE REVIEW

**Comment by watou** [comment]
@querdenker2k Are your Eclipse IDE formatting rules up to date and in effect?

**Comment by querdenker2k** [comment]
I hope so. I am not an eclipse user.
Are there some special formatting rules for openhab?

**Comment by 9037568** [comment]
Here's the [IDE Setup](http://docs.openhab.org/developers/development/ide.html) guide.

If you install Eclipse using these instructions you automatically get the formatter. I wish we had a document describing the code formatting rules, but alas I'm not aware of any such...

**Comment by querdenker2k** [comment]
I can't get it to work.
I tried it on 3 days, but it can't be the problem.
I did it as described, but every time the same error.
There is enough space, tried different java versions, different eclipse versions, but no success.

Do you have an idea?

> Executing bootstrap tasks
> Java(TM) SE Runtime Environment 1.8.0_20-b26
> Product org.eclipse.products.epp.package.java.neon
> Project com.github.openhab2.1_infra.master
> Project com.github.openhab2.2_openhab2.master
> Project com.github.openhab2.3_openhab1.master
> Bundle org.eclipse.oomph.setup 1.6.0.v20161125-0947, build=2774, branch=0f3cbae74af4fe94d13c32afb96e9cd4ad2194b7
> Bundle org.eclipse.oomph.setup.core 1.6.0.v20161128-0928, build=2774, branch=0f3cbae74af4fe94d13c32afb96e9cd4ad2194b7
> Bundle org.eclipse.oomph.setup.installer 1.6.0.v20161114-1007, build=2774, branch=0f3cbae74af4fe94d13c32afb96e9cd4ad2194b7
> Bundle org.eclipse.oomph.setup.p2 1.6.0.v20161019-0656, build=2774, branch=0f3cbae74af4fe94d13c32afb96e9cd4ad2194b7
> Performing Workspace C:\Users\Robert\Java-Workspace\openhab\openhab2\openhab2-master2\ws
> Performing P2 Director (Eclipse IDE for Java Developers (Neon))
> Offline = false
> Mirrors = true
> Resolving 32 requirements from 5 repositories to C:\Users\Robert\Java-Workspace\openhab\openhab2\openhab2-master2\eclipse
> Requirement org.eclipse.wst.xml_ui.feature.feature.group
> Requirement org.eclipse.mylyn.java_feature.feature.group
> Requirement org.codehaus.groovy.eclipse.feature.feature.group
> Requirement org.eclipse.mylyn.git.feature.group
> Requirement org.eclipse.pde.feature.group
> Requirement org.eclipse.wst.jsdt.feature.feature.group
> Requirement org.eclipse.wst.web_ui.feature.feature.group
> Requirement epp.package.java [4.6.0,4.7.0)
> Requirement org.eclipse.platform.feature.group [4.6.0,4.7.0)
> Requirement org.eclipse.rcp.feature.group [4.6.0,4.7.0)
> Requirement org.eclipse.buildship.feature.group
> Requirement org.eclipse.egit.feature.group
> Requirement org.eclipse.egit.mylyn.feature.group
> Requirement org.eclipse.jdt.feature.group
> Requirement org.eclipse.jgit.feature.group
> Requirement org.eclipse.m2e.feature.feature.group
> Requirement org.eclipse.m2e.logback.feature.feature.group
> Requirement org.eclipse.mylyn.bugzilla_feature.feature.group
> Requirement org.eclipse.mylyn.context_feature.feature.group
> Requirement org.eclipse.mylyn.hudson.feature.group
> Requirement org.eclipse.mylyn.ide_feature.feature.group
> Requirement org.eclipse.mylyn.wikitext_feature.feature.group
> Requirement org.eclipse.mylyn_feature.feature.group
> Requirement org.eclipse.recommenders.mylyn.rcp.feature.feature.group
> Requirement org.eclipse.recommenders.rcp.feature.feature.group
> Requirement org.eclipse.recommenders.snipmatch.rcp.feature.feature.group
> Requirement org.eclipse.oomph.setup.feature.group
> Requirement org.eclipse.oomph.setup.jdt.feature.group
> Requirement org.eclipse.oomph.setup.git.feature.group
> Requirement org.eclipse.oomph.setup.workingsets.feature.group
> Requirement org.eclipse.oomph.setup.projects.feature.group
> Requirement org.eclipse.oomph.setup.pde.feature.group
> Repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/
> Repository http://download.eclipse.org/technology/epp/packages/neon
> Repository http://download.eclipse.org/releases/neon/201610111000
> Repository http://download.eclipse.org/oomph/updates/milestone/latest
> Repository http://download.eclipse.org/egit/updates
> Adding repository http://download.eclipse.org/egit/updates
> Fetching p2.index from http://download.eclipse.org/releases/neon/201610111000/
> Adding repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/
> Fetching p2.index from http://download.eclipse.org/releases/neon/201610111000/
> Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
> Fetching p2.index from http://download.eclipse.org/technology/epp/packages/neon/
> Adding repository http://download.eclipse.org/releases/neon/201610111000
> Adding repository http://download.eclipse.org/technology/epp/packages/neon
> Fetching content.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/ (19,35kB)
> Calculating requirements and dependencies.
> Computing prerequisite plan
> Fetching artifacts.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/ (1,82kB)
> Collecting 1 artifacts from http://download.eclipse.org/technology/epp/packages/neon
> Downloading epp.package.java.executable.win32.win32.x86_64
> Collected 1 artifacts for http://download.eclipse.org/technology/epp/packages/neon in 0.766s
> Collecting 19 artifacts from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/
> Downloading org.codehaus.groovy.eclipse
> Downloading org.codehaus.groovy.jdt.patch
> Downloading org.codehaus.groovy.eclipse.ant
> Downloading org.codehaus.groovy.eclipse.feature
> Downloading org.codehaus.groovy23.feature
> Downloading org.codehaus.groovy.compilerless.feature
> Downloading org.codehaus.groovy.headless.feature
> Downloading org.codehaus.groovy.eclipse.compilerResolver
> Downloading org.codehaus.groovy.eclipse.astviews
> Downloading org.codehaus.groovy
> Fetching org.codehaus.groovy.eclipse.astviews_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (61,29kB)
> Fetching org.codehaus.groovy.jdt.patch_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/ (9,19kB)
> Fetching org.codehaus.groovy.compilerless.feature_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/ (15,1kB)
> Fetching org.codehaus.groovy.headless.feature_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/ (14,88kB)
> Fetching org.codehaus.groovy.eclipse.ant_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (11,73kB)
> Fetching org.codehaus.groovy.eclipse_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (8,96kB)
> Fetching org.codehaus.groovy23.feature_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/ (14,72kB)
> Fetching org.codehaus.groovy.eclipse_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (8,96kB)
> Fetching org.codehaus.groovy.eclipse.ant_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (11,73kB)
> Fetching org.codehaus.groovy_2.3.11.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (8,21MB)
> Fetching org.codehaus.groovy.eclipse.compilerResolver_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (15,92kB)
> Fetching org.codehaus.groovy23.feature_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/ (14,72kB)
> Fetching org.codehaus.groovy_2.3.11.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (8,21MB)
> Fetching org.codehaus.groovy.eclipse.compilerResolver_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (15,92kB)
> Fetching org.codehaus.groovy.eclipse.feature_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/features/ (14,85kB)
> Downloading org.eclipse.jdt.core
> Downloading org.codehaus.groovy.eclipse.ui
> Downloading org.codehaus.groovy.eclipse.dsl
> Fetching org.codehaus.groovy_2.3.11.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/
> Downloading org.eclipse.jdt.groovy.core
> Downloading org.codehaus.groovy.eclipse.refactoring
> Downloading org.codehaus.groovy.eclipse.codeassist.completion
> Downloading org.codehaus.groovy.eclipse.core
> Downloading org.codehaus.groovy.eclipse.quickfix
> Downloading org.codehaus.groovy.eclipse.codebrowsing
> Fetching org.eclipse.jdt.core_3.12.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (5,59MB)
> Fetching org.codehaus.groovy.eclipse.dsl_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (374,27kB)
> Fetching org.codehaus.groovy.eclipse.codebrowsing_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (76,88kB)
> Fetching org.eclipse.jdt.groovy.core_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (350,59kB)
> Fetching org.codehaus.groovy.eclipse.refactoring_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (252,3kB)
> Fetching org.codehaus.groovy.eclipse.core_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (98,37kB)
> Fetching org.codehaus.groovy.eclipse.ui_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (462,92kB)
> Fetching org.codehaus.groovy.eclipse.codeassist.completion_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (207,04kB)
> Fetching org.codehaus.groovy.eclipse.quickfix_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (91,39kB)
> Fetching org.codehaus.groovy.eclipse.ui_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (462,92kB)
> Fetching org.codehaus.groovy.eclipse.codeassist.completion_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (207,04kB)
> Fetching org.eclipse.jdt.core_3.12.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/
> Fetching org.codehaus.groovy.eclipse.quickfix_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/ (91,39kB)
> Fetching org.codehaus.groovy.eclipse.codebrowsing_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/
> Fetching org.codehaus.groovy.eclipse.refactoring_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/
> Fetching org.eclipse.jdt.groovy.core_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/
> Fetching org.codehaus.groovy.eclipse.core_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/
> Fetching org.codehaus.groovy.eclipse.ui_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/
> Fetching org.codehaus.groovy.eclipse.dsl_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/
> Fetching org.codehaus.groovy.eclipse.quickfix_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/
> Fetching org.codehaus.groovy.eclipse.codeassist.completion_2.9.2.xx-201612101823-e46.jar from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/plugins/
> Mirrored 19 artifacts from http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/ at 204kb/s
> Collected 19 artifacts for http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/ in 13.684s
> Collecting 3 artifacts from http://download.eclipse.org/releases/neon/201610111000
> Downloading org.eclipse.platform.ide.executable.win32.win32.x86_64
> Downloading org.eclipse.platform_root
> Downloading org.eclipse.rcp_root
> Collected 3 artifacts for http://download.eclipse.org/releases/neon/201610111000 in 0.566s
> The engine operation was cancelled and the changes are being rolled back.
> Took 49 seconds.
> Task execution was canceled.
> Press Back to choose different settings or Cancel to abort.

**Comment by 9037568** [comment]
This is from trying to install Eclipse?

Afraid I can't be of any help there. I didn't install from the command-line. Did it at least create a log file you can post to an Eclipse help forum?

**Comment by 9037568** [comment]
@querdenker2k, can you provide information on what this change does? Possibly a sample configuration?

**Comment by querdenker2k** [comment]
I just followed the IDE setup guide. What information do you need?

**Comment by 9037568** [comment]
I was going to fix the formatting and push this change in, but I couldnt' find a description of the change.

I was looking for a description of what your changes actually do. (ie. What new capabilities do they add to Caldav, how are they used, etc?) so that I could update the documentation in the README.

**Comment by querdenker2k** [comment]
Ah sorry, is just read my last comment, not the topic.
This property is for bind the calendar id (which is defined in the cfg) to an item.
Like this: 
`String Calendar	"Aus Kalender [%s]"	<calendar>	{ caldavPersonal="calendar:private,work type:UPCOMING eventNr:1 value:CALENDAR" }`

This is not documented because it was not merged.

**Comment by 9037568** [comment]
Can I prevail upon you to submit a change for the README.md file? That way we can merge it all at once...

**Pull request closed without merging**
