### PR TITLE
Implement the ability to change the wall thermostat display mode

### PR DESCRIPTION
**Pull request by cyclingengineer**
This allows you to change the wall stat display to either the current temperature or the current setpoint.

In theory this can be done at pairing time as well, but I've disabled that at the moment as it doesn't appear to work and it seems to stall the pairing process.

This also includes a refactoring of the pairing message sequence state machine to make it more understandable.

Tested on my local setup. Wiki documentation updated.

### CODE REVIEW

**Comment by teichsta** [comment]
@cyclingengineer could you please:

* announce your changes at https://community.openhab.org and find other Testers of this change
* squash your commits into one
* test the maxcul binding against the OH2 platform and report your results as PR here: https://github.com/openhab/openhab2/blob/master/docs/sources/addons.md#compatible-1x-add-ons

Thanks, Thomas E.-E.

**Comment by teichsta** [comment]
any new @cyclingengineer?

**Comment by teichsta** [comment]
move this PR to 1.9

**Comment by 9037568** [comment]
Is @cyclingengineer still planning to finish this PR?

**Pull request closed without merging**
