### PR TITLE
[Cups] Upgrade cups binding to the newest cups4j library

### PR DESCRIPTION
**Pull request by 9037568**
This library update has added support for slf4j logging within the library (though it doesn't appear to be used yet).

There's also one small multibyte character bug fix.

### CODE REVIEW

**Comment by watou** [comment]
There is still an 0.6.3 in the `.classpath` file. 😄

**Comment by 9037568** [comment]
Oops :)

**Comment by watou** [comment]
😄  Does this fix a bug and should be in 1.9.1, or is this just good maintenance and can wait for 1.10.0?

**Comment by 9037568** [comment]
No, no bug fixing involved. It can wait for 1.10.0.

**Pull request merged**
