### PR TITLE
moved networkupstools to legacy addons

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by wborn** [comment]
There are also a couple of other add-ons that still need to be moved to legacy, see: https://github.com/openhab/openhab1-addons/issues/5882, https://github.com/openhab/openhab1-addons/issues/5895

**Comment by kaikreuzer** [comment]
Right, see https://github.com/openhab/openhab-distro/pull/982#issuecomment-541540388.

**Comment by kaikreuzer** [comment]
@cweitkamp, @wborn, @Hilbrand, @martinvw I took the liberty and added you to the openHAB 1.x addons maintainer team - this should make it easier for you to also merge such PRs :-)

**Comment by wborn** [comment]
Thanks! :+1:

**Pull request merged**
