### PR TITLE
Binding for Philips TVs with jointspace API

### PR DESCRIPTION
**Pull request by Lenzebo**
I created a binding for my Philips TV into openhab. All their models (since 2011) support a json-based api called jointSPACE (see http://jointspace.sourceforge.net/projectdata/documentation/jasonApi/index.html for the reference what one can do with it) that allows controlling some functionality over ethernet.

Right now the binding can:
- Send Button commands
- Sets and Read Volume/Mute
- Set and Get Colors of Ambilight "Pixels"

### CODE REVIEW

**Comment by Baumi1245** [comment]
Hello!
@Lenzebo hope this is the right place: will this binding be available for OH2?
I was in contact with Philips-Support yesterday - they wrote, that new TV-Sets still have Joint Space running...

Thank you.

**Comment by Lenzebo** [comment]
@Baumi1245 
Thanks for the interest. Unfortunately I haven't had much time look into openhab2 but it seems to be pretty straightforward. 
Maybe the current version will already work with the compatibility layer but I haven't tried it yet

As I also still control my TV with it, I was planning on integrating it into OH2 but I cannot give you a particular date for that.

**Comment by watou** [comment]
@Lenzebo @Baumi1245 if you put the [JAR](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.jointspace/target/org.openhab.binding.jointspace-1.9.0-SNAPSHOT.jar) in your OH2 addons folder and supply the proper configuration, it could very well work under OH2 as it does under OH1.  If you find that it does work, small pull requests like [this one](https://github.com/openhab/openhab/pull/4743/files) and [this one](https://github.com/openhab/openhab-docs/pull/127) would be all that is needed to make it installable under openHAB 2.  If it does not work on openHAB 2, it will need to be investigated before adding it as described.

**Comment by Lenzebo** [comment]
I just verified that the binding works as expected under OH2 and will make the small pull request that it will be installable. 
I will make a full OH2 integration as soon as time permits :)

**Comment by watou** [comment]
Excellent news -- thanks! 😄

**Pull request merged**
