### PR TITLE
move mail action to legacy

### PR DESCRIPTION
**Pull request by J-N-K**
openhab2 has a mail binding now

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by openhab-5iver** [comment]
Is this something to make note of in the distro? It's not really breaking, but for people who do not have legacy enabled, the old action might disappear for them.

**Comment by J-N-K** [comment]
Yes. I‘ll prepare a PR.

**Comment by kaikreuzer** [comment]
@J-N-K Seems this was lingering around too long, sorry. Could you please rebase the PR? Thanks!

**Comment by J-N-K** [comment]
@openhab/1-x-add-ons-maintainers, can this be merged now?

**Pull request merged**
