### PR TITLE
[km200] Bugfixes and preparation for OH2 Binding

### PR DESCRIPTION
**Pull request by Markinus**
* Changed the internal data structure to a tree based one (Preparations für Things)
* Changed the error handling in case of communication problems 
* Added a method to automatic device detection (can be overriden in the config)

### CODE REVIEW

**Comment by watou** [comment]
@Markinus Is this PR complete?  If so, does it fix bug(s) in the binding included in the OH 2.0.0 release and therefore should be part of the next maintenance release, or is it an enhancement only?  Thanks!

**Comment by Markinus** [comment]
Yes, it is, it's a combination.
It's a bugfix in case there are some problems on the network connection. The second part are some enhancemends as preparation for OH2 Binding. (The code is almost same now). 
It should be part of the  next maintenance release.

**Comment by watou** [comment]
@Markinus Could you rebase this PR to master, which will bring in the README.md, and add edits to that to match the .cfg changes and any other improvements?  Thank you!

**Comment by Markinus** [comment]
OK, I did it, I hope it's that what you wanted?

**Comment by watou** [comment]
I don't see a new commit here?

**Comment by Markinus** [comment]
I think I need a bit help on that what you want. This PR is based on master. In master the readme file is already marged. If I understand you correctly then the commit with the README should be a part of this PR too, right? (so it can be marged in the 1.9.1 branch). But how? (the only missing thing is the readme file, sorry but I'm not sure how to do it).

**Comment by watou** [comment]
If you rebase your PR branch to the current master branch, this will bring in the README.md file which this can PR can then have edits to.  I sometimes look at [this article](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) to refresh my memory on rebasing pull requests, in case it helps.

**Comment by Markinus** [comment]
Hi @watou, sorry for the long time but I was very busy. I rebased it to master now.

**Pull request closed without merging**
