### PR TITLE
[dynamodb] java8 compatibility

### LINKED ISSUE #5030: DynamoDB Persistence Service has build problem
Hi @ssalonen,

I believe this repo is being built for Java 8 now (https://github.com/openhab/openhab1-addons/commit/2a1b7e1f88eaf313fa7d48b36edce0ac97fcc491), and this is a new build error:

```log
12:25:49.663  |  [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.24.0:compile (default-compile) on project org.openhab.persistence.dynamodb: Compilation failure: Compilation failure:
12:25:49.663  |  [ERROR] /scratch/jenkins/workspace/openHAB1-Addons/bundles/persistence/org.openhab.persistence.dynamodb/java/org/openhab/persistence/dynamodb/internal/DynamoDBPersistenceService.java:[323]
12:25:49.663  |  [ERROR] paginatedList = mapper.query(dtoClass, queryExpression);
12:25:49.663  |  [ERROR] ^^^^^
12:25:49.664  |  [ERROR] The method query(Class<T>, DynamoDBQueryExpression<T>) in the type AbstractDynamoDBMapper is not applicable for the arguments (Class<capture#19-of ? extends DynamoDBItem<?>>, DynamoDBQueryExpression<DynamoDBItem<?>>)
12:25:49.664  |  [ERROR] 1 problem (1 error)
12:25:49.664  |  [ERROR] -> [Help 1]
12:25:49.664  |  [ERROR] 
12:25:49.664  |  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
12:25:49.664  |  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
12:25:49.664  |  [ERROR] 
12:25:49.665  |  [ERROR] For more information about the errors and possible solutions, please read the following articles:
12:25:49.665  |  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
12:25:49.665  |  [ERROR] 
12:25:49.665  |  [ERROR] After correcting the problems, you can resume the build with the command
12:25:49.665  |  [ERROR]   mvn <goals> -rf :org.openhab.persistence.dynamodb
```

Would you have an opportunity to have a look?

See also #5028 and https://github.com/openhab/openhab1-addons/commit/f7787764b93748c2e8465a697b7f0688c424acb8

### PR DESCRIPTION
**Pull request by ssalonen**
Attempt to fix #5030

Also restores building of dynamodb (reverts f7787764b93748c2e8465a697b7f0688c424acb8)

### CODE REVIEW

**Comment by ssalonen** [comment]
@watou could you please confirm this works as expected?

Also, when debugging this I noticed that there are different kind of definitions for the JRE in `.classpath`, e.g. `<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7"/>`. What is the implication of the setting?

Many of the bundles are still referring to [JavaSE-1.7](https://github.com/openhab/openhab1-addons/blob/master/bundles/persistence/org.openhab.persistence.jdbc/.classpath) or [JavaSE-1.6](https://github.com/openhab/openhab1-addons/blob/master/bundles/persistence/org.openhab.persistence.caldav/.classpath), while [some](https://github.com/openhab/openhab1-addons/blob/master/bundles/action/org.openhab.action.ecobee/.classpath) do not define the Java version. Is this by design?

Best,
Sami

**Comment by watou** [comment]
I built your branch with `mvn clean install` and it succeeded, but first I had to uncomment the module from `persistence/pom.xml`.  Could you push the same on your branch and then this PR LGTM.  Thanks very much, Sami.

**Comment by ssalonen** [comment]
Now the dynamodb is uncommented also in `persistence/pom.xml`

**Comment by watou** [comment]
Thank you!

**Pull request merged**
