### PR TITLE
adds optional host to help with discovery across subnets

### PR DESCRIPTION
**Pull request by digitaldan**
Signed-off-by: Dan Cunningham <dan@digitaldan.com>

### CODE REVIEW

**Comment by watou** [comment]
@digitaldan Is this a bug whose fix should appear in the next 1.9.1 maintenance release, or an enhancement that can wait for 10.0.0?

**Comment by digitaldan** [comment]
I would vote for 1.9.1, this PR is in part due to Logitech changing the login in such a way that made the 1.x binding not usable.  Its also a minor change to how the binding works.

**Comment by kaikreuzer** [comment]
>  can wait for 10.0.0?

Oh, that will take long (unless you meant 1.10.0) ;-)

**Comment by watou** [comment]
> Oh, that will take long (unless you meant 1.10.0) ;-)

Oops. ;-)

**Comment by watou** [comment]
cherry picked onto 1.9.x

**Pull request merged**
