### PR TITLE
[Tinkerforge] support for new Bricklets

### PR DESCRIPTION
**Pull request by andiikaa**
As promised in #5785, some new bindings are supported.

This PR:
* updates the tinkerforge model directory path to `org.openhab.binding.tinkerforge1`
* updates the tinkerforge.jar to `2.1.22`
* supports [Dual Button Bricklet V2](https://www.tinkerforge.com/en/doc/Hardware/Bricklets/Dual_Button_V2.html)
* supports [Load Cell Bricklet V2](https://www.tinkerforge.com/en/doc/Hardware/Bricklets/Load_Cell_V2.html)
* supports [NFC Bricklet](https://www.tinkerforge.com/en/doc/Hardware/Bricklets/NFC.html)
* supports [RGB LED Button Bricklet](https://www.tinkerforge.com/de/shop/rgb-led-button-bricklet.html)

I will later add the support for the following bricklets:
* [OLED 128x64 Bricklet 2.0](https://www.tinkerforge.com/de/shop/oled-128x64-v2-bricklet.html)
* [LCD 128x64 Bricklet](https://www.tinkerforge.com/de/shop/lcd-128x64-bricklet.html)

Note: It seems that the tinkerforge xcore model wasn't touched for while. My changes seems to trigger the auto format for all model files.

Signed-off-by: André Kühnert <andre.kuehnie@gmail.com> (github: andiikaa)

### CODE REVIEW

**Comment by andiikaa** [comment]
I added the missing OLED 128x64 Bricklet 2.0 and LCD 128x64 Bricklet.
I noticed, that the OLED 64x48 Bricklet and OLED 128x64 Bricklet 1.0 are also implemented but are missing in the readme, so i added a (really) short description.

This will close #5785.

Signed-off-by: André Kühnert andre.kuehnie@gmail.com (github: andiikaa)

**Comment by theoweiss** [comment]
Just had a very quick look add the diffs. Looks promising. I'm really short of time in these days, may be some one else could review the requirements which are not tinkerforge specific @watou @9037568 and I will do the remaining review? Among others I'm working on a openhab2 tinkerforge binding.

**Comment by theoweiss** [comment]
Almost forgotten: @andiikaa thanks for the PR!

**Comment by kaikreuzer** [comment]
Sorry to see that this is hanging since forever without a review.
@andiikaa & @theoweiss Do you still want to pursue this or is it meanwhile outdated as there are better options to use Tinkerforge in openHAB 2 by now?

**Comment by andiikaa** [comment]
For me it is not that important that it gets merged. My project is done and i don´t have access to the bricklets anymore.
I´ve just seen that there is now a [Binding Generator](https://github.com/Tinkerforge/generators) directly from tinkerforge, but i did not compare which bricklets are supported for now. 

With the generator it should also be easy to add new bricklets. So in my opinion this OH1 binding gets outdated really fast. So no one should invest much time in it.

**Comment by theoweiss** [comment]
A beta of the new OH2 binding is available from here https://www.tinkerunity.org/topic/4901-betaversion-der-openhab-bindings/ (de) or here https://www.tinkerunity.org/topic/4909-beta-version-of-the-openhab-bindings/ (en). 
The binding is evolving fast and now supports most of the available bricklets. It works with openHAB 2.5.0~M*.
Hopefully the TinkerForge people will make a PR to contribute the binding to the official openHAB stack: https://www.tinkerunity.org/topic/4901-betaversion-der-openhab-bindings/page/4/?tab=comments#comment-28099 (de).
I think new TF users should use the new binding and current users should switch to the new binding as soon as they need support for a bricklet which is not supported with the OH1 binding.
I agree with André and suggest to abandon the work on the OH1 TinkerForge binding and to close this PR.

**Comment by kaikreuzer** [comment]
Ok, many thanks for your opinions - so let's close this PR then.

**Pull request closed without merging**
