### PR TITLE
removed myopenhab and openhabcloud bundles as both are not buildable in 1.9 anymore

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@watou this should also be picked for the 1.9.x branch, although it will have no impact on the build results.

**Comment by watou** [comment]
Thanks, will do.

**Comment by kaikreuzer** [comment]
So don't forget to merge, I'll come up with another important PR afterwards ;-)

**Comment by watou** [comment]
picked onto 1.9.x

**Pull request merged**
