### PR TITLE
[fatekplc] Added serial port support

### PR DESCRIPTION
**Pull request by slawekjaranowski**
fix: #5871

### CODE REVIEW

**Comment by Marcin-st** [comment]
Started working after upgrade openhab M2 to M4

**Comment by slawekjaranowski** [comment]
I kindly ask about review @openhab/1-x-add-ons-maintainers

**Comment by 9037568** [comment]
@Marcin-st please clarify your statement. Are you saying that the problem you filed in #5871 is no longer occurring for you? If it is not, please close that ticket.

@slawekjaranowski if that problem is no longer occurring, this PR is not needed?

**Comment by slawekjaranowski** [comment]
The issue #5871 report that fatekplc binding doesn't have support to communicate by serial line / serial port with plc.

This PR add such possibility, so extends functionality and is needed.

**Comment by slawekjaranowski** [comment]
During test we talked with marcin on https://community.openhab.org/t/fatek-binding-to-use-usb-cabel/74509

So text "Started working after upgrade openhab M2 to M4" means that this PR start morking.

**Comment by Marcin-st** [comment]
Confirm. Fatek now is working with Serial-USB cabel.

**Pull request merged**
