### PR TITLE
RFXCom Lighting4 Message

### PR DESCRIPTION
**Pull request by AlexF12004Roma**
Add support for RFXCom Lighting4
SubType PT2262

### CODE REVIEW

**Comment by federic0** [comment]
Hi, I'm trying to implement a Switch for a Lighting4 device (Elro plug) with OpenHAB and rfxcom. This is rfxcom's manager output ON and OFF commands:
Packettype    = Lighting4
subtype       = PT2262
Sequence nbr  = 114
Code          = 001151 decimal:4433
S1- S24  = 0000 0000 0001 0001 0101 0001 
Pulse         = 364 usec
Signal level  = 8
------------------------------------------------
Packettype    = Lighting4
subtype       = PT2262
Sequence nbr  = 115
Code          = 001154 decimal:4436
S1- S24  = 0000 0000 0001 0001 0101 0100 
Pulse         = 359 usec
Signal level  = 8


How would I implement the switch with the rfxcom binding?

Thanks.

**Comment by AlexF12004Roma** [comment]
In source code comments (RFXComLighting4Message.java) you can find and example of my binding.

here it is:

 a Lighting4 Base command is composed of 24 bit DATA plus PULSE information
+ * 
+ * DATA:
+ * Code          = 014554
+ * S1- S24  = <0000 0001 0100 0101 0101> <0100>
+ * first 20 are DeviceID last 4 are for Command 
+ * 
+ * PULSE:
+ * default 350
+ * 
+ * Tested on a PT2262 remote PlugIn module
+ * 
+ * Example: 
+ * 
+ * Switch TESTout  "TestOut" (All) {rfxcom=">83205.350:LIGHTING4.PT2262:Command"}
+ * (SendCommand  DeviceID(int).Pulse(int):LIGHTING4.Subtype:Command  )
+ * 
+ * Switch TESTin  "TestIn" (All) {rfxcom="<83205:Command"} 
+ * (ReceiveCommand ON/OFF Command  )
+ * 
+ * @author Alessandro Ballini (ITA)
+ * @since 1.5.1

**Comment by federic0** [comment]
Thanks Alex,

I had seen your example but I am unable to understand it or to get it to work, I dont’ understand: "SendCommand DeviceID(int).Pulse(int):LIGHTING4.Subtype:Command”.

Thanks for your help

**Comment by AlexF12004Roma** [comment]
Here is my Switch in sitemap
Switch TESTout "TestOut" (All) {rfxcom=">83205.350:LIGHTING4.PT2262:Command"}

You have to log your command with rfxcommManager
and convert the 24 bit string and replace DviceID,Command.

* S1- S24 = <0000 0001 0100 0101 0101> <0100>
* first 20 are DeviceID last 4 are for Command

**Comment by federic0** [comment]
Thanks, I understand now.

**Comment by federic0** [comment]
Hi Alex,

This is what rfxcom manager is picking up (ON/OFF):

Packettype    = Lighting4
subtype       = PT2262
Sequence nbr  = 114
Code          = 001151 decimal:4433
S1- S24  = 0000 0000 0001 0001 0101 0001 
Pulse         = 364 usec
Signal level  = 8
------------------------------------------------
Packettype    = Lighting4
subtype       = PT2262
Sequence nbr  = 115
Code          = 001154 decimal:4436
S1- S24  = 0000 0000 0001 0001 0101 0100 
Pulse         = 359 usec
Signal level  = 8

So converting from binary to decimal:  0000 0000 0001 0001 0101 = 277 
This is my item in home.items

Switch TESTout  "TestOut" (PrimeraPlanta) {rfxcom=">277.350:LIGHTING4.PT2262:Command"} 

I’m I doing it right?

Thanks for your help

**Comment by hazymat** [comment]
Hi Alex

This doesn't make sense - the example you gave S1- S24 = <0000 0001 0100 0101 0101> <0100> converts in decimal to 83284, not 83205 as you said. Or am I missing something?

My switch is S1- S24  = 0000 0001 0100 0100 0101 0100 (OFF) which converts to 83028. My subtype is the same as yours so it should be:

Switch TESTout "TestOut" (All) {rfxcom=">83028.350:LIGHTING4.PT2262:Command"}

But this doesn't work at all.

Can you tell me what the item definition should be for me?

**Comment by federic0** [comment]
Hi, any updates on these issues?

**Comment by federic0** [comment]
Hi Alex,

I would greatly appreciate your help.
rfxcom manager oputputs this for a wall plug:
Packettype    = Lighting4
subtype       = PT2262
Sequence nbr  = 108
Code          = 000551 decimal:1361
S1- S24  = 0000 0000 0000 0101 0101 0001 
Pulse         = 362 usec
Signal level  = 8
------------------------------------------------
Packettype    = Lighting4
subtype       = PT2262
Sequence nbr  = 109
Code          = 000554 decimal:1364
S1- S24  = 0000 0000 0000 0101 0101 0100 
Pulse         = 364 usec
Signal level  = 8


The following item will turn the light ON
Switch wallplug "Led” {rfxcom=">1361.360:LIGHTING4.PT2262:Command”} 

However, I am unable to turn it OFF, I have also tried:

Switch wallplug "Led” {rfxcom=">1364.360:LIGHTING4.PT2262:Command”}

Thanks

Fedderico

**Comment by Speederc** [comment]
HI  @federic0 and @hazymat,
I compiled a new version which should fix the problem with lighting4 devices : http://dr-petelot-marion.chirurgiens-dentistes.fr/temp/org.openhab.binding.rfxcom_1.9.0.201601221259.jar .
For your sensors, using the 20 first bits as sensorID, it should work with :
   - frederic0 : {rfxcom=">85.360:LIGHTING4.PT2262:Command"}
   - hazymat : {rfxcom=">5189.350:LIGHTING4.PT2262:Command"}
Can you test it and give me your feedback ?

Thanks

**Pull request merged**
