### PR TITLE
added add-on distribution again and added diyonxbee binding to the build

### PR DESCRIPTION
**Pull request by kaikreuzer**
This PR adds a "addons.zip" again, which can be distributed as a download.

@watou I took this from the 1.8 branch and added all new add-ons from [this list](https://github.com/openhab/openhab1-addons/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Aclosed%20label%3Anew-binding-action-service%20milestone%3A1.9.0%20is%3Amerged) - I hope this is complete. Would be good if you could double check.

And of course: This needs to be picked for 2.0.x!

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by watou** [comment]
That's great, Kai!  I will check it over later this evening.  Thanks for that.

**Comment by watou** [comment]
distribution/pom.xml and distribution/src/assemble/addons.xml should be formatted (tabs and spaces), but more importantly, not sure what to make of this:

```
$ git status
On branch pr/5013
Your branch is up-to-date with 'origin/pr/5013'.
nothing to commit, working directory clean
$ git log | head
commit a87e21b15ccedaa332c426fdf92cfabed01f52d4
Author: Kai Kreuzer <kai@openhab.org>
Date:   Thu Jan 19 18:27:32 2017 +0100

    added add-on distribution again and added diyonxbee binding to the build
    
    Signed-off-by: Kai Kreuzer <kai@openhab.org>

commit be371c2c1b0616a4c73fb618c11d09fcd56f9483
Author: Kai Kreuzer <kai@openhab.org>
$ mvn clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Project 'org.openhab:openhab:1.9.0-SNAPSHOT' is duplicated in the reactor @ 
[ERROR] Project 'org.openhab:openhab:1.9.0-SNAPSHOT' is duplicated in the reactor -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DuplicateProjectException
```

**Comment by kaikreuzer** [comment]
oops, give me a second...

**Comment by kaikreuzer** [comment]
Ok, fixed it. Please have a try now!

**Comment by watou** [comment]
checking....

**Comment by watou** [comment]
Built successfully.  Missing addons from the resulting .zip file:

* binding/org.openhab.binding.garadget
* binding/org.openhab.binding.plclogo
* persistence/org.openhab.persistence.dynamodb

I will go tag those PRs now, but once you add the above missing addons, LGTM.

**Comment by watou** [comment]
19 new addons since 1.8:

3 new actions, 15 new bindings, 1 new persistence service
```
action/org.openhab.action.pebble
action/org.openhab.action.pushsafer
action/org.openhab.action.satel
binding/org.openhab.binding.ddwrt
binding/org.openhab.binding.diyonxbee
binding/org.openhab.binding.expire
binding/org.openhab.binding.fatekplc
binding/org.openhab.binding.garadget
binding/org.openhab.binding.gc100ir
binding/org.openhab.binding.horizon
binding/org.openhab.binding.km200
binding/org.openhab.binding.mcp23017
binding/org.openhab.binding.mcp3424
binding/org.openhab.binding.plclogo
binding/org.openhab.binding.powerdoglocalapi
binding/org.openhab.binding.powermax
binding/org.openhab.binding.smarthomatic
binding/org.openhab.binding.upb
persistence/org.openhab.persistence.dynamodb
```

**Comment by kaikreuzer** [comment]
Many thanks for checking!
I have now added the missing add-ons as well, so we should be good to merge.

**Comment by watou** [comment]
cherry picked onto 1.9.x

**Pull request merged**
