### PR TITLE
Removed persistence services

### PR DESCRIPTION
**Pull request by kaikreuzer**
Related to https://github.com/openhab/openhab-core/pull/680

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by yveshanoulle** [comment]
confused, I thought that there were no persistence services exist in 2.0 ?

**Comment by kaikreuzer** [comment]
Just read the linked https://github.com/openhab/openhab-core/pull/680.

**Comment by wborn** [comment]
I think this PR can be closed? OH 2.5.x still uses OH1 persistence add-ons and all OH1 add-ons have been removed from OH3. The applicable add-ons were migrated to OH3 in https://github.com/openhab/openhab-addons/pull/5275.

**Comment by kaikreuzer** [comment]
Indeed.

**Pull request closed without merging**
