### PR TITLE
u::Lux binding

### PR DESCRIPTION
**Pull request by abrenk**
This is the openHAB binding for u::Lux switches (http://www.u-lux.com/) previously developed in its own repository at https://github.com/abrenk/openhab-ulux-binding.

History was rewritten using `git filter-branch --tree-filter` to move the files to their proper location.

For documentation see [bundles/binding/org.openhab.binding.ulux/README.md](https://github.com/abrenk/openhab/blob/ulux-binding/bundles/binding/org.openhab.binding.ulux/README.md).

@teichsta Please review and merge.

This resolves issue #493.

### CODE REVIEW

**Comment by teichsta** [comment]
Thanks @abrenk for this contribution! Fyi i won't be able to start reviewing before mid of August. Hope to start earlier though. Thanks for your patience, Thomas E.-E.

**Comment by teichsta** [comment]
unfortunately i didn't manage to review this binding up to now (and i am very sorry for that). Will move to 1.9 though …

**Comment by 9037568** [comment]
I'm beginning a review of this. For starters, it needs to be run through the eclipse formatter.

**Comment by 9037568** [comment]
@abrenk, I see a lot of TODOs. Does the README.md reflect only the things that are fully functional? If not, you should add some notes about which features are not fully functional.

**Pull request closed without merging**
