### PR TITLE
TinkerForge: Fix AmbientLightV2 Lux values

### PR DESCRIPTION
**Pull request by theoweiss**
AmbientLightV2 measures 1/100 Lux values not 1/10 Lux.
The auto formatter wants even more changes ;-( .

### CODE REVIEW

**Comment by 9037568** [comment]
There are a number of instances of code changes to blocks like this one where the curly braces have been removed. That seems to be contrary to the code convention. Did your formatter do this?

I don't see any of these changes when I run the Eclipse formatter...


````
if (eNotificationRequired()) {
             eNotify(new ENotificationImpl(this, Notification.SET, ModelPackage.BRICKLET_OLED_CONFIGURATION__INVERT, oldInvert, invert));
}
````

**Comment by theoweiss** [comment]
I've rerun the formatter and as well see no changes. Do I have to apply any updates to the ide? I use an oomph installed eclipse. The initial installation is quite old and if I execute "Check for Updates" lots of updates are proposed.

Formatter settings:
eclipseformatter

Another option is to disable the formatter for the generated code:
https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.tinkerforge/model/tinkerforge.xcore#L11 setting:

```
codeFormatting="false"
```

???

**Comment by 9037568** [comment]
I don't know about the IDE setup. I dislike that everything depends on installing the IDE from scratch in just the right way... but that's a digression for another time.

Kai had suggested [over here in this thread](https://github.com/openhab/openhab-distro/pull/344#issuecomment-265725006) to use [the official oomph profile](https://github.com/openhab/openhab-distro/blob/master/launch/openHAB2.setup).

**Comment by theoweiss** [comment]
> Kai had suggested over here in this thread to use the official oomph profile.

That's what I did a year ago. What's really not obvious to me is how to upgrade the ide.

I've reverted the format changing commit.

**Comment by theoweiss** [comment]
@9037568 is there any chance to get this into 2.0.0?

**Comment by watou** [comment]
cherry picked onto 1.9.x branch so it should appear in OH 2.0.0

**Comment by theoweiss** [comment]
Thanks @watou that's great.

**Pull request merged**
