### PR TITLE
[FS20] Update FS20Command.java

### PR DESCRIPTION
**Pull request by DanielZils**
Add commands from FS20STR temperature device and motion sensor:
TEMP_SYNC("37"), // when forced to sync
TEMP_OFF("38"), // when temperature higher than threshold means OFF
TEMP_ON("39"), // when temperature lower than threshold means ON
MOTION_ON("3E"), // PIR detected motion, timed ON

### CODE REVIEW

**Review by 9037568 — CHANGES_REQUESTED** [review]
Please put these in the right order (below TOGGLE).

**Comment by DanielZils** [comment]
> Please put these in the right order (below TOGGLE).

Done.

**Review by 9037568 — APPROVED** [review]
LGTM.

**Comment by 9037568** [comment]
@openhab/maintainers I don't see a reason for this build failure. Any insights?

**Comment by cniweb** [comment]
@DanielZils You have unsigned commits:
https://github.com/openhab/openhab1-addons/pull/5931/checks

**Comment by DanielZils** [comment]
> @DanielZils You have unsigned commits:
> https://github.com/openhab/openhab1-addons/pull/5931/checks

Unfortunately, I don't have permission. (Sorry, I'm totally a rookie...)

**Comment by 9037568** [comment]
>fatal: unable to access 'https://github.com/openhab/openhab1-addons.git/': The requested URL returned error: 403

Wrong repo. You should still be pushing to your original branch.

**Review by 9037568 — CHANGES_REQUESTED** [review]
Whoops.

**Pull request closed without merging**
